import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";
const api = "http://localhost:8000";
type Alert = { id:string; payee:string; tier:string; reason_codes:string[]; at:string };
function App() {
 const [alerts,setAlerts]=useState<Alert[]>([]); const [notice,setNotice]=useState("Listening for new payment signals.");
 async function refresh(){const r=await fetch(`${api}/v1/ops/alerts`);setAlerts((await r.json()).alerts)}
 useEffect(()=>{void refresh();const id=setInterval(()=>void refresh(),3000);return()=>clearInterval(id)},[]);
 async function simulate(){await fetch(`${api}/v1/risk/score`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({payer_vpa:"asha@bankA",payee_vpa:"quickcash77@bankC",amount_inr:24500,channel:"collect",timestamp:new Date().toISOString(),lang:"en"})});setNotice("Synthetic collector-mule scenario injected. The alert feed has refreshed.");void refresh()}
 return <main><aside><div className="logo">S</div><strong>SETU Shield</strong><nav><a>Overview</a><a className="active">Live alerts</a><a>Federation</a><a>Model card</a><a>Privacy</a></nav><small>Synthetic demo environment</small></aside><section className="content"><header><div><p>Fraud operations</p><h1>Payment safety monitor</h1></div><button onClick={()=>void simulate()}>Run scam simulation</button></header><p className="notice">{notice}</p><div className="grid"><article className="wide"><h2>Live alerts <span>{alerts.length}</span></h2>{alerts.length ? alerts.map(a=><div className="alert" key={a.id}><i className={a.tier}/><div><strong>{a.payee}</strong><p>{a.reason_codes.join(" · ")}</p></div><time>{new Date(a.at).toLocaleTimeString()}</time></div>):<p className="empty">No live alerts. Run the synthetic scam simulation to see the cross-bank mule path.</p>}</article><article><h2>Ring view</h2><div className="graph"><b>Asha<br/><small>Bank A</small></b><em>→</em><b className="risk">QuickCash<br/><small>Bank C</small></b><em>→</em><b className="risk">Mule 02<br/><small>Bank B</small></b><em>→</em><b>Sink<br/><small>Bank A</small></b></div><p>Cross-bank edges are visible only as model signals; raw payment data stays with each participating bank.</p></article><article><h2>Federation</h2><div className="bars"><span style={{height:"35%"}}/><span style={{height:"49%"}}/><span style={{height:"63%"}}/><span style={{height:"71%"}}/><span style={{height:"78%"}}/></div><p>Demo policy active. Training metrics are intentionally not shown until the full experiment is run.</p></article><article><h2>Privacy boundary</h2><ul><li>Raw account data stays local</li><li>Demo uses synthetic inputs</li><li>Advisory, fail-open scoring</li></ul></article></div></section></main> }
createRoot(document.getElementById("root")!).render(<App/>);

